language: r
sudo: required
cache: packages
dist: trusty

env:
  global:
  - R_BUILD_ARGS="--no-manual"
  - R_CHECK_ARGS="--as-cran --no-manual"

addons:
  apt:
    packages:
      - python-dev

before_install:
  - pip install --user numpy bibtexparser

notifications:
  email:
    on_success: never
    on_failure: never
  
