language: r
sudo: false
cache: packages
dist: trusty

env:
  global:
  - R_BUILD_ARGS="--no-manual"
  - R_CHECK_ARGS="--as-cran --no-manual"

before_install:
  - pip install bibtexparser

notifications:
  email:
    on_success: never
    on_failure: never
  
